#!/usr/bin/env bash
# nginx port 80 debugging
# How to fix it: delete the existing default file in the ../sites-available dir
# Replace it with the default file in the site enabled dir
# create a symbolic link for this
# note: -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
